### ISSUE TITLE
AXFR seems to hang

### ISSUE THREAD

**Issue by jawnsy** [peterhellberg/xip.name#1]
Dear maintainer,

Thank you for your work! This looks like a very useful tool indeed.

I saw the code has some handling for `AXFR` and `IXFR` requests, however, when I run with `dig`, it appears to just hang (no output from `dig` until timeout, and no output on the server either, even running in verbose mode)

Here's the command I'm running:

`dig test.1.2.3.4.xip.name axfr @localhost +authority`

Interestingly, when using the production system, no result is returned (possibly dropped by an intermediate DNS server?) and testing with https://hackertarget.com/zone-transfer/ yields no results.  I'm not sure what the AXFR requests are supposed to return other than the SOA information in normal requests (empty zone?)

Some additional thoughts:
- Even if `fqdn` is passed, information for `xip.name` will always be returned (it's hardcoded): https://github.com/peterhellberg/xip.name/blob/master/xip.go#L116
  - The serial number is also hardcoded, which seems like it'd cause problems with `IXFR` requests
- Errors are swallowed instead of returned from `handleDNS` or logged to `stderr`, even in verbose mode: https://github.com/peterhellberg/xip.name/blob/master/xip.go#L112

Jonathan

**Comment by peterhellberg** [comment]
Note that this service was hacked together over a week end, when [xip.io](http://xip.io/) happened to be down and a friend of mine needed something like it.

I have not touched this code in quite some time (before tonight, I’m in **GMT+2**)

**Comment by jawnsy** [comment]
@peterhellberg No worries, I don't expect any sort of support or SLA from you (I'm not demanding free work - in fact I'm willing to contribute). Just filed the issue because I like this tool and your service, and always try to report bugs :smile:
