### ISSUE TITLE
Regular expression not anchored

### ISSUE THREAD

**Issue by jawnsy** [peterhellberg/xip.name#3]
Hello,

The regular expression used to pattern match is not anchored, so it looks for an IP address anywhere in the requested hostname. I'm unsure whether this is the expected behaviour.

Example:

```
$ dig test.1.2.3.4.hello.xip.name

; <<>> DiG 9.10.4-P2-RedHat-9.10.4-1.P2.fc25 <<>> test.1.2.3.4.hello.xip.name
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39814
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;test.1.2.3.4.hello.xip.name.   IN  A

;; ANSWER SECTION:
test.1.2.3.4.hello.xip.name. 300 IN A   1.2.3.4

;; Query time: 439 msec
;; SERVER: 172.20.0.1#53(172.20.0.1)
;; WHEN: Tue Sep 27 11:32:27 PDT 2016
;; MSG SIZE  rcvd: 72
```

I'd suggest using a regular expression, checking that the domain suffix matches the defined FQDN, and checking the return value of `net.ParseIP` (you might be seeing panics in the server logs for something that matches the regexp but isn't a valid IP address). Happy to submit a PR if you'd like :smile:

For example (probably causes a panic due to ParseIP returning nil, since the IP is invalid):

```
$ dig test.999.2.3.4.hello.xip.name

; <<>> DiG 9.10.4-P2-RedHat-9.10.4-1.P2.fc25 <<>> test.999.2.3.4.hello.xip.name
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 25744
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;test.999.2.3.4.hello.xip.name. IN  A

;; Query time: 472 msec
;; SERVER: 172.20.0.1#53(172.20.0.1)
;; WHEN: Tue Sep 27 11:32:44 PDT 2016
;; MSG SIZE  rcvd: 58
```

**Comment by peterhellberg** [comment]
`dig test.999.2.3.4.hello.xip.name` will [not cause a panic](https://play.golang.org/p/iRaTN1hydi), but it will obviously not return an IP number in the A-record.

Matching something that looks sort of an IP number anywhere in the hostname before `.xip.name.` is the expected behaviour.

**Comment by jawnsy** [comment]
Okay, thanks!

Personally, I'd think it'd be better to return an NXDOMAIN response rather than SERVFAIL. Compare (note the status):

```
$ dig sdgsdg.google.com

; <<>> DiG 9.10.4-P2-RedHat-9.10.4-1.P2.fc25 <<>> sdgsdg.google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 3553
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;sdgsdg.google.com.		IN	A

;; AUTHORITY SECTION:
google.com.		60	IN	SOA	ns1.google.com. dns-admin.google.com. 134432093 900 900 1800 60

;; Query time: 78 msec
;; SERVER: 172.20.0.1#53(172.20.0.1)
;; WHEN: Tue Sep 27 12:25:59 PDT 2016
;; MSG SIZE  rcvd: 96
```

**Comment by jawnsy** [comment]
It's interesting that it doesn't cause a panic, too, since `ParseIP` really does return `nil` - https://play.golang.org/p/EuXTWBLRpv

**Comment by peterhellberg** [comment]
`nil` is a valid `net.IP` since that type is a `[]byte`

<https://play.golang.org/p/x9QVtgWTMM>
