### ISSUE TITLE
Consider relicensing under BSD license

### ISSUE THREAD

**Issue by jawnsy** [peterhellberg/xip.name#5]
Hello,

Upstream code and examples are under two variants of the BSD license:

* The library itself (https://github.com/miekg/dns/) is under the 3-clause BSD license: https://github.com/miekg/dns/blob/master/LICENSE
* Example code (https://github.com/miekg/exdns/) is under the 2-clause BSD license: https://github.com/miekg/exdns/blob/master/LICENSE

Please consider relicensing your utility with one of these BSD licenses as it makes it easier for legal folk to evaluate.

Cheers,

Jonathan

**Comment by peterhellberg** [comment]
I was thinking the same last night, will relicense when I get the time.
